"""Finding codes — the single source of truth for everything the classifier emits."""

from __future__ import annotations

from enum import StrEnum


class FindingCode(StrEnum):
    # Trust-policy structural / classifier-emitted
    ROLE_USED_BY_MULTIPLE_CLUSTERS = "ROLE_USED_BY_MULTIPLE_CLUSTERS"
    CROSS_ACCOUNT_TRUST = "CROSS_ACCOUNT_TRUST"
    WILDCARD_SUB = "WILDCARD_SUB"
    MULTI_SUB_FORALL = "MULTI_SUB_FORALL"
    CUSTOM_AUD_CLAIM = "CUSTOM_AUD_CLAIM"
    PERMISSION_BOUNDARY = "PERMISSION_BOUNDARY"
    STALE_ANNOTATION = "STALE_ANNOTATION"
    DEFAULT_SA_ANNOTATED = "DEFAULT_SA_ANNOTATED"
    OPERATOR_MANAGED = "OPERATOR_MANAGED"
    MIXED_PRINCIPAL_EC2 = "MIXED_PRINCIPAL_EC2"
    SESSION_NAME_TOO_LONG = "SESSION_NAME_TOO_LONG"
    STS_TAGSESSION_PRESENT = "STS_TAGSESSION_PRESENT"
    MULTI_STATEMENT_OIDC = "MULTI_STATEMENT_OIDC"
    NON_STANDARD_AUD_CLAIM = "NON_STANDARD_AUD_CLAIM"
    FOREIGN_OIDC_ISSUER = "FOREIGN_OIDC_ISSUER"

    # IAM lookup failures (driven by audit, not the rule predicates)
    ROLE_NOT_FOUND = "ROLE_NOT_FOUND"
    POLICY_PARSE_ERROR = "POLICY_PARSE_ERROR"

    # Apply-time pre-flight
    POD_IDENTITY_AGENT_MISSING = "POD_IDENTITY_AGENT_MISSING"

    # Pod-spec scan
    CUSTOM_TOKEN_FILE_PATH = "CUSTOM_TOKEN_FILE_PATH"

    # Verify
    VERIFY_DEFERRED = "VERIFY_DEFERRED"
    VERIFY_STILL_IRSA = "VERIFY_STILL_IRSA"
